name: geany-plugins
version: 1.28-snap1  # the version of the snap
summary: Set of plugins for Geany
description: A packaging containing a set of plugins for Geany
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

slots:
  geany-plugins-slot:
    content: geany-plugins-all
    interface: content
    read:
    - /

parts:
    all-plugins:
        plugin: autotools
        source: git@github.com:geany/geany-plugins.git
        source-type: git
        configflags: [--enable-gtk3=yes --enable-all-plugins]
        build-packages: # from .travis.yml
            - libgtk2.0-dev
            - libgtk-3-dev
            - intltool
            - libtool
            - python-docutils
            - check
            # FIXME: there are weird error with spellcheck and Ubuntu 12.04's version of cppcheck (1.52)
            - cppcheck
            # debugger
            - libvte-dev
            # devhelp
            - libwebkitgtk-dev
            - libwnck-dev
            - libgconf2-dev
            - zlib1g-dev
            # geanygendoc
            - libctpl-dev
            # geanylua
            - liblua5.1-0-dev
            # geanypg
            - libgpgme11-dev
            # geanypy
            - python-dev
            - python-gtk2-dev
            # geanyvc
            - libgtkspell-dev
            - libgtkspell3-3-dev
            # geaniuspaste/updatechecker
            - libsoup2.4-dev
            # git-changebar
            # Ubuntu 12.04 doesn't have libgit2, 14.04 has a too old one, so we build
            # our own for now.
            #- libgit2-dev
            # markdown
            - libmarkdown2-dev
            # markdown/webhelper
            - libwebkitgtk-3.0-dev
            # multiterm
            - valac
            # pretty-printer
            - libxml2-dev
            # spellcheck
            - libenchant-dev

            # for libgit2 build
            - cmake      
