name: tyrant-unleashed-optimizer
version: daily
summary: Tyrant Unleashed Optimizer
description: |
  Simulator app for the game Tarant Unleashed that can be used to optimize your
  card deck for certain raids, or temporary buffs as well as growth planning in
  general.

confinement: strict

apps:
  sim:
    command: usr/bin/tuo.exe
    plugs: [home]

  updatexml:
    command: usr/bin/update_xml.sh
    plugs: [home, network]

parts:
  tyrant-unleashed-optimizer:
    plugin: x_toumakefixup
    source: https://github.com/andor9/tyrant_optimize.git
    source-type: git
    stage-packages: [git]
    build-packages: [g++, make, build-essential, libboost1.58-dev]
    stage-packages:
      - curl
