name: grive
version: 'master'
summary: An open source Linux client for Google Drive
description: |
  This is the up-to-date fork of the original "Grive"
  Google Drive client with the support for the new Drive REST API and partial
  sync.
  .
  For the first time running grive, you should use the "-a" argument to grant
  permission to grive to access to your Google Drive. An URL should be printed.
  Go to the page. You will need to login to your google account if you haven't
  done so. After granting the permission to grive, the browser will show you
  an authenication code. Copy-and-paste that to the standard input of grive.
  If everything works fine, grive will create .grive and .grive_state inside the
  synchronized directory. It will also start downloading files from your Google
  Drive to that directory.

grade: devel
confinement: strict

apps:
  grive:
    command: grive
    plugs: [home, network, unity7]

parts:
  grive:
    source: https://github.com/vitalif/grive2.git
    plugin: cmake
    build-packages:
      - cmake
      - build-essential
      - libgcrypt11-dev
      - libyajl-dev
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libcppunit-dev
      - binutils-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - binutils
      - libboost-filesystem1.58.0
      - libboost-program-options1.58.0
      - libboost-regex1.58.0
      - libboost-system1.58.0
      - libc6
      - libcurl3
      - libgcc1
      - libgcrypt20
      - libstdc++6
      - libyajl2
