name: imagemagick-stable
version: 6.9.7
summary: ImageMagick is a software suite to create, edit, or convert bitmap images.
description: |
    ImageMagick can read and write images in a variety of formats (over 200)
    including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF,
    and SVG.  Use ImageMagick to resize, flip, mirror, rotate, distort, shear
    and transform images, adjust image colors, apply various special effects,
    or draw text, lines, polygons, ellipses and Bézier curves.

    This snap is a kitchen-sink, every-option build of the current version of IM6.
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    animate:
        command: animate
    compare:
        command: compare
    composite:
        command: composite
    conjure:
        command: conjure
    convert:
        command: convert
    display:
        command: display
    identify:
        command: identify
    import:
        command: import
    magick:
        command: magick
    magick-stream:
        command: magick-stream
    mogrify:
        command: mogrify
    montage:
        command: montage
    stream:
        command: stream

parts:
    imagemagick:
        plugin: autotools
        source: http://git.imagemagick.org/repos/ImageMagick/repository/archive.tar.bz2?ref=ImageMagick-6
        source-type: tar
        configflags:
            - --enable-hdri=yes
            - --enable-shared=yes
            - --enable-static=yes
            - --with-autotrace=yes
            - --with-fpx=no
            - --with-gnu-ld=yes
            - --with-gslib=yes
            - --with-modules=no
            - --with-quantum-depth=32
            - --with-rsvg=yes
        build-packages:
            - autoconf
            - build-essential
            - fftw-dev
            - libautotrace-dev
            - libbz2-dev
            - libdjvulibre-dev
            - libfftw3-dev
            - libfontconfig1-dev
            - libfreetype6-dev
            - libgs-dev
            - libgvc6
            - libjbig-dev
            - libjpeg-dev
            - liblcms2-dev
            - liblqr-1-0-dev
            - libltdl-dev
            - libmagick++-dev
            - libopenexr-dev
            - libopenjp2-7-dev
            - libpango1.0-dev
            - libperl-dev
            - libpng12-dev
            - librsvg2-dev
            - libtiff5-dev
            - libwebp-dev
            - libwmf-dev
            - libx11-dev
            - lzma-dev
            - ocl-icd-opencl-dev
            - perlmagick
            - zlib1g-dev
