name: geany
version: 1.28-snap3
summary: A fast and lightweight IDE using GTK+
description: Geany is a small and lightweight integrated development environment.
 It was developed to provide a small and fast IDE, which has only a
 few dependencies from other packages. It is using only the GTK2 toolkit
 and therefore you need only the GTK2 runtime libraries to run Geany.

confinement: strict

apps:
  geany:
    command: gtk-launch geany
    plugs: [x11, unity7, home]

parts:
    geany:
        plugin: autotools
        source: git://github.com/geany/geany.git
        source-type: git
        configflags: [--enable-binreloc, --enable-gtk3, --prefix=/usr, -disable-html-docs ]
        build-packages:
            - build-essential
            - intltool
            - libgdk-pixbuf2.0-dev
            - libgtk-3-dev
        stage-packages:
            - dconf-gsettings-backend
            - libgtk-3-0            
            - python-gi
            - ttf-ubuntu-font-family
            - unity-gtk3-module
            - adwaita-icon-theme

    launcher:
        plugin: copy
        files:
            gtk-launch: bin/gtk-launch
