name: geany
version: 1.28-snap1
summary: A fast and lightweight IDE using GTK+
description: This is my-snap's description  # a longer description for the snap
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  geany:
    command: gtk-launch geany
    plugs: [x11, unity7, home]

parts:
    geany:
        plugin: autotools
        source: git://github.com/geany/geany.git
        source-type: git
        configflags: [--enable-gtk3, --prefix=/usr, -disable-html-docs ]
        build-packages:
            - build-essential
            - intltool
            - libgdk-pixbuf2.0-dev
            - libgtk-3-dev
        stage-packages:
            - dconf-gsettings-backend
            - libgtk-3-0            
            - python-gi
            - gir1.2-gtk-3.0
            - gir1.2-gtksource-3.0
            - ttf-ubuntu-font-family

    launcher:
        plugin: copy
        files:
            gtk-launch: bin/gtk-launch
