name: ps-mem
version: "3.8"
summary: A utility to accurately report the core memory usage for a program
description: |

confinement: devmode

apps:
  ps-mem:
    command: usr/bin/ps_mem

parts:
  ps-mem:
    plugin: python3
    source: https://github.com/pixelb/ps_mem.git
