name: ffmpeg
version: 3.0~git
summary: Tools for transcoding, streaming and playing of multimedia files
description: |
    FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
    mux, demux, stream, filter and play pretty much anything that humans and
    machines have created. It supports the most obscure ancient formats up to the
    cutting edge.
    This package contains;
      ffmpeg - a command line tool to convert multimedia files between formats
      ffserver - a multimedia streaming server for live broadcasts
      ffplay - a simple media player based on SDL and the FFmpeg libraries
      ffprobe - a simple multimedia stream analyzer
      qt-faststart - a utility to rearrange Quicktime files
# ffcfstress fmpeg ffmpeg2theora ffmvforce fset ftest
confinement: devmode


apps:
  ffmpeg:
    command: ffconvert
    plugs: [ home ]
  ffserver:
    command: ffserver
    plugs: [ home ]
  ffplay:
    command: ffplay
    plugs: [ home ]
  ffprobe:
    command: ffprobe
    plugs: [ home ]
  qt-faststart:
    command: qt-faststart
    plugs: [ home, unity7, x11 ]

parts:
  launcher:
    plugin: copy
    files:
      ffmpeg: bin/ffmpeg
      ffserver: bin/ffserver
      ffplay: bin/ffplay
      ffprobe: bin/ffprobe
      qt-faststart: bin/qt-faststart

  ffmpeg:
    plugin: autotools
    configflags: 
        - --disable-ffplay
        - --disable-ffserver
        - --disable-ffprobe
        - --enable-gpl
        - --enable-libass
        - --enable-libfreetype
        - --enable-libmp3lame
        - --enable-libopus
        - --enable-libtheora
        - --enable-libvorbis
        - --enable-libvpx
        - --enable-libx264
        - --enable-libx265
        - --enable-nonfree
    source: git://source.ffmpeg.org/ffmpeg.git
    source-type: git
    build-packages:
        - autoconf
        - automake
        - build-essential
        - cmake
        - g++
        - git
        - libass-dev
        - libfreetype6-dev
        - libmp3lame-dev
        - libopus-dev
        - libsdl1.2-dev
        - libtheora-dev
        - libtool
        - libva-dev
        - libvdpau-dev
        - libvorbis-dev
        - libvpx-dev
        - libx264-dev
        - libx265-dev
        - libxcb-shm0-dev
        - libxcb-xfixes0-dev
        - libxcb1-dev
        - make
        - pkg-config
        - texinfo
        - yasm
        - zlib1g-dev
    stage-packages:
        - x265
